### ISSUE TITLE
MongoClient opened before fork

### ISSUE THREAD

**Issue by HrTran** [plantpark/scaleable-crawler-with-docker-cluster#2]
Last night, when I ran `python -m test_celery.run_tasks`, anyone knows how to fix it?
```
worker_1    | [2018-05-19 05:12:06,257: WARNING/ForkPoolWorker-3] /usr/local/lib/python2.7/site-packages/pymongo/topology.py:145: UserWarning: MongoClient opened before fork. Create MongoClient with connect=False, or create client after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#pymongo-fork-safe>
worker_1    |   "MongoClient opened before fork. Create MongoClient "
```
and 
```
worker_1    | [2018-05-19 05:12:36,612: ERROR/ForkPoolWorker-3] Task test_celery.tasks.longtime_add[287b7121-cb07-42b5-868b-785e6aab74cc] raised unexpected: ServerSelectionTimeoutError('127.0.0.1:27017: [Errno 111] Connection refused',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/test_celery/tasks.py", line 17, in longtime_add
worker_1    |     raise self.retry(exc=exc)
worker_1    |   File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 668, in retry
worker_1    |     raise_with_context(exc)
worker_1    |   File "/app/test_celery/tasks.py", line 14, in longtime_add
worker_1    |     post.insert({'status':r.status_code,"creat_time":time.time()}) # store status code and current time to mongodb
worker_1    |   File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 2467, in insert
worker_1    |     with self._socket_for_writes() as sock_info:
worker_1    |   File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
worker_1    |     return self.gen.next()
worker_1    |   File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
worker_1    |     server = self._get_topology().select_server(selector)
worker_1    |   File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
worker_1    |     address))
worker_1    |   File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
worker_1    |     self._error_message(selector))
worker_1    | ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
```

Currently, I have
```
pymongo==3.6.1
celery==4.1.0
python==3.5.2
Ubuntu==16.04
```

**Comment by tonywangcn** [comment]
Try the latest push, if any problems please reopen it.

**Comment by HrTran** [comment]
I still got the error @tonywangcn

**Comment by tonywangcn** [comment]
could you show me more info about your problems?
